server:
  port: 8080
spring:
  application:
    name: hm-gateway  #服务名称
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.100:8848 # nacos地址 消费者
    gateway:
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**, /search/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/addresses/**, /users/**



logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

